name: Deploy Laravel App to EC2 with RDS Connection

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 Public IP or DNS
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Deploying Laravel App to EC2..."

            # Step 1: Create the app directory if it doesn't exist
            sudo mkdir -p /var/www/laravel-app

            # Step 2: Navigate to the directory
            cd /var/www/laravel-app

            # Step 3: Clone the Laravel repository from GitHub
            git clone https://github.com/laravel/laravel.git .

            # Step 4: Set permissions
            sudo chown -R ubuntu:ubuntu /var/www/laravel-app

            # Step 5: Install Composer if it's not installed
            if ! command -v composer &> /dev/null
            then
              echo "Composer not found, installing..."
              curl -sS https://getcomposer.org/installer | php
              sudo mv composer.phar /usr/local/bin/composer
            fi

            # Step 6: Install Laravel app dependencies
            composer install

            # Step 7: Generate Laravel app key
            php artisan key:generate

            # Step 8: Run migrations (this will connect to the RDS MySQL)
            php artisan migrate --force

            # Step 9: Set proper permissions for storage and cache
            sudo chown -R www-data:www-data storage bootstrap/cache

            # Step 10: Restart Apache or NGINX (based on your setup)
            sudo systemctl restart apache2
