name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Get the latest code from the repository

    - name: Build Docker image
      run: docker build -t laravel-app .  # Build the Laravel app Docker image

    - name: Run Laravel migrations
      run: |
        docker run --rm -e APP_ENV=local laravel-app php artisan migrate --force  # Run migrations with --force

    - name: Run Laravel container
      run: |
        docker run -d --name laravel-app -p 8000:8000 laravel-app  # Start the container after migrations

    - name: Check Laravel status
      run: curl -s http://localhost:8000  # Verify that the Laravel app is running (on port 80)