name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Get the latest code from the repository

    - name: Build Docker image
      run: docker build -t laravel-app .  # Build the Laravel app Docker image

    - name: Run Laravel container
      run: |
        docker run -d --name laravel-app -p 80:8000 laravel-app  # Bind container's port 8000 to host's port 80

    - name: Run Laravel migrations
      run: docker exec laravel-app php artisan migrate  # Run database migrations inside the running container

    - name: Check Laravel status
      run: curl -s http://localhost  # Verify that the Laravel app is running (on port 80)
