name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for the runner

    steps:
    # Step 1: SSH into the remote server
    - name: SSH into EC2 and set up the app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Setting up Laravel app on EC2..."

          # Create a directory for the Laravel app if it doesn't exist
          if [ ! -d "/home/ubuntu/laravel-app" ]; then
            echo "Creating Laravel app directory..."
            mkdir -p /home/ubuntu/laravel-app
          fi

          # Navigate to the directory
          cd /home/ubuntu/laravel-app

          # Pull the latest code from the repository
          echo "Pulling the latest code..."
          git pull origin main || git clone https://github.com/AmirKaseb/Obelion-Task-Backend.git .

          # Build Docker image 
          docker build -t laravel-app .

          # Run migrations (if needed)
          docker run --rm -e APP_ENV=local laravel-app php artisan migrate --force

          # Run Laravel container
          docker run -d --name laravel-app -p 8000:8000 laravel-app
